### ISSUE TITLE
add API for breaking dependency chain upon user request

### ISSUE THREAD

**Issue by smacke** [nbsafety-project/nbsafety#21]

**Comment by ruiduoray** [comment]
Now it's allowing to refresh the staleness upon override. This is maybe a safer idea than to break the chain

**Comment by smacke** [comment]
@ruiduoray I think this strategy makes more sense. It may still make sense to allow breaking the dependency change if explicitly requested, so I'll leave this issue open under a different title. Probably not as high priority compared to the change you already made.

**Comment by smacke** [comment]
I actually haven't needed this functionality much in practice, so will go ahead and close.
